### PR TITLE
Completed assignment involving Shell and git commands to download log…

### PR DESCRIPTION
**Pull request by amitsindhwani**
…s files and copy server, user and events logs in respective folders

## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
Added shell scripts to create directories and move the server, user and event log files to specific sub-directories created under data directory. The specific comments include the reasons for choosing a specific scripts.

## What did you learn from the changes you have made?
I learnt about how to create directories, find the specific files using wildcards, redirect names of all the files in a specific directory into a text file. Also I learnt about how the general flow of how to initialize git, use credential manager, clone your repo, work on a local branch and push your changes to staging, committing and pushing it to the repo. 

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
I have tried options like creating directory one by one but alternative way to create all subdirectories in one go using {}
Tries ls and redirected the file names to a text file, but find command was more efficient to push only the files and not including the subdirectories.

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
Yes there were many challenges, scripts commands to ensure that i am writing the correct script. Worked mostly in GUI interface and command line took a while to adopt!
Understanding the flow and how GIT works, branching concepts etc. was a new to me. I have previous experience of working in VSS and SVN versioning tools! so mapping took a while. Took help from ChatGPT and "https://www.geeksforgeeks.org/git-tutorial/?ref=outind" website helped understand it better.

## How were these changes tested?
I tested these commands on the terminal before pushing my changes to repository

## Checklist
- [Yes] I can confirm that my changes are working as intended
I tested running the script on a separate folder

### CODE REVIEW

**Comment by monzchan** [comment]
@amitsindhwani Good work! Please do not merge next time, but leave the PR open for 'your coworker' to review.

**Comment by amitsindhwani** [comment]
> @amitsindhwani Good work! Please do not merge next time, but leave the PR open for 'your coworker' to review.

Sure @monzchan! thanks for reviewing! will take care of it in future!

**Comment by monzchan** [comment]
@amitsindhwani You may have missed the part 2 of the assignment for resolving conflicts. Please have a look at the assignment_instruction file and finish part 2. You are just one step to perfect!

**Comment by anjali-deshpande-hub** [comment]
Hi Amit, 
Also, in future, please don't delete the branch for the pull request.
You will also notice that the autograder did not run for your PR. This is because your 'main' branch is out of sync with the forked directory. Please follow the instructions in this thread to fix the problem:  https://uoft-dsi-certificates.slack.com/archives/C07VC7M4PTL/p1732596801781119

**Pull request merged**
